### ISSUE TITLE
[BUG] Cannot run from bdist_wheel

### ISSUE THREAD

**Issue by zobayer1** [zobayer1/elastic-migrate#7]
### TL;DR
Currently package built with `python setup.py sdist bdist_wheel` can be installed, but fails to execute.

**Expected behavior**
Should be able to run `esmigrate` and observe output on the terminal.

**Observed behavior**
Fails with error
```sh
(venv) [zobayer@hyperion dist]$ esmigrate 
Traceback (most recent call last):
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/bin/esmigrate", line 5, in <module>
    from esmigrate.cli import main
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/esmigrate/cli.py", line 4, in <module>
    from esmigrate.contexts import ContextConfig
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/esmigrate/contexts/__init__.py", line 2, in <module>
    from esmigrate.contexts.context_config import ContextConfig
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/esmigrate/contexts/context_config.py", line 8, in <module>
    from esmigrate.commons import local_config_file_path, user_config_file_path
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/esmigrate/commons/__init__.py", line 19, in <module>
    version = get_version(root="../../", relative_to=__file__)
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/setuptools_scm/__init__.py", line 144, in get_version
    return _get_version(config)
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/setuptools_scm/__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages/setuptools_scm/__init__.py", line 110, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/home/zobayer/Projects/opensource/staging/elastic-migrate/venv/lib64/python3.8/site-packages'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

### Reproduction
1. Run `python bdist_wheel`
2. Install the `.whl` package using `pip install` in a venv
3. Run `esmigrate`

**Environment**

- OS: (e.g. Fedora 32)
- Python: (e.g. 3.8)
- SQL DB: (e.g. Sqlite3)
- Elastic: (e.g. 5.6)

**Additional information**

**Comment by zobayer1** [comment]
Created this SO post.
https://stackoverflow.com/q/62730254/2613150
